export const SET_LIST_VIEW_SCROOL_TOP = "GLOBAL/SET_LIST_VIEW_SCROOL_TOP";
export const SET_HEADER_CEILING_FLAG = "GLOBAL/SET_HEADER_CEILING_FLAG";
export const SET_PATH_NAME = "GLOBAL/SET_PATH_NAME";
export const SET_TAB_KEY = "GLOBAL/SET_TAB_KEY";
export const SET_FEEDBACKMODAL = "GLOBAL/FEEDBACKMODAL";
export const GET_USER = "GLOBAL/GET_USER";
export const SET_USER = "GLOBAL/SET_USER";
export const INIT_PAGE = "GLOBAL/INIT_PAGE";
export const CLICK_SILD_BAR = "GLOBAL/CLICK_SILD_BAR";
export const CHAGE_USER_SLID = "GLOBAL/CHAGE_USER_SLID";
export const GET_CONFIG_INDEX_PAGE = "GLOBAL/GET_CONFIG_INDEX_PAGE";
export const SET_CONFIG_INDEX_PAGE = "GLOBAL/SET_CONFIG_INDEX_PAGE";
export const GO_TO_RECHAGE = "GLOBAL/GO_TO_RECHAGE";

