export const SET_LIST_VIEW_SCROOL_TOP = "GLOBAL/SET_LIST_VIEW_SCROOL_TOP";
export const SET_HEADER_CEILING_FLAG = "GLOBAL/SET_HEADER_CEILING_FLAG";
export const SET_PATH_NAME = "GLOBAL/SET_PATH_NAME";
export const SET_TAB_KEY = "GLOBAL/SET_TAB_KEY";


